//V1.0 2019-05-10 Waves
/*******************************************************************************************************************
V1.1 2019-06-26 HKZ
增加
//打饮类
#define MAKE_DRINK_CODE_SEG	    		(uint32_t)121000
#define	MAKE_DRINK_NORMAL				 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_0,0)		//121000	//打饮正常
#define	MAKE_DRINK_NO_LIQUOR			ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_3,1)			//121301	//未检测到酒
#define	MAKE_DRINK_NO_CUP				 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_3,2)		//121302	//未检测到杯
#define	MAKE_DRINK_REVISE				 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_3,3)		//121303	//打饮校正失败
#define	MAKE_DRINK_OUTIME				 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_3,4)		//121304	//打饮超时

#define	MAKE_DRINK_AIR_PRESSURE_ERR		 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_2,1)		//121205	//气压异常：可能是气泵不工作、管道破裂
//电控锁
#define	LOCK_CODE_SEG	           (uint32_t)122000
#define	LOCK_NORMAL		           ERR_CODE(LOCK_CODE_SEG,ERR_LEVEL_0,0)		//122000		//开锁正常		 	
#define	LOCK_BLOCK		           ERR_CODE(LOCK_CODE_SEG,ERR_LEVEL_3,1)		//122301		//开锁失败		
#define	LOCK_OUTIME		           ERR_CODE(LOCK_CODE_SEG,ERR_LEVEL_3,1)		//122202		//开锁超时	
***********************************************************************************************************************/

/****************************************************************************************************
V1.2 2019-06-26 Waves
增加
#define GOODS_IR_NOTPICK        ERR_CODE(GOODS_IR_CODE_SEG,ERR_LEVEL_4,3)  //检测到未取货
#define GOODS_GATE_UNFULLCLOSE  ERR_CODE(GOODS_GATE_CODE_SEG,ERR_LEVEL_1,4)  //防盗门未关闭
#define GOODS_GATE_UNCLOSE      ERR_CODE(GOODS_GATE_CODE_SEG,ERR_LEVEL_1,5)  //防盗门未关闭

#define GOODS_INNERGATE_CODE_SEG           (uint32_t)108000
#define GOODS_INNERGATE_NORMAL             ERR_CODE(GOODS_INNERGATE_CODE_SEG,0,0)  //防盗门正常
#define GOODS_INNERGATE_UNFULLOPEN         ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,1)  //防盗门未完全打开
#define GOODS_INNERGATE_UNOPEN             ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,2)  //防盗门未打开
#define GOODS_INNERGATE_OFFLIN             ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,3)  //防盗门离线
#define GOODS_INNERGATE_UNFULLCLOSE        ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,4)  //防盗门未关闭
#define GOODS_INNERGATE_UNCLOSE            ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,5)  //防盗门未关闭

#define GOODS_OUTERGATE_CODE_SEG     (uint32_t)109000
#define GOODS_OUTERGATE_NORMAL       ERR_CODE(GOODS_OUTERGATE_CODE_SEG,0,0)  //防盗门正常
#define GOODS_OUTERGATE_UNFULLOPEN   ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,1)  //防盗门未完全打开
#define GOODS_OUTERGATE_UNOPEN       ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,2)  //防盗门未打开
#define GOODS_OUTERGATE_OFFLIN       ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,3)  //防盗门离线
#define GOODS_OUTERGATE_UNFULLCLOSE  ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,4)  //防盗门未关闭
#define GOODS_OUTERGATE_UNCLOSE      ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,5)  //防盗门未关闭

******************************************************************************************************/

/****************************************************************************************************
V1.3 2019-07-19 HKZ
增加
#define	GOODS_ACK_CODE_SEG				(uint32_t)113000
#define	GOODS_ACK_NORMAL				ERR_CODE(GOODS_ACK_CODE_SEG,0,0)				//响应正常
#define	GOODS_ACK_MESSAGE_EXPIRATION	ERR_CODE(GOODS_ACK_CODE_SEG,ERR_LEVEL_3,1)  	//消息过期
#define	GOODS_ACK_TIME_NOT_SYNC			ERR_CODE(GOODS_ACK_CODE_SEG,ERR_LEVEL_3,2)		//时间未同步
#define	GOODS_ACK_SELL_BUSY				ERR_CODE(GOODS_ACK_CODE_SEG,ERR_LEVEL_3,3)		//出货忙
#define	GOODS_ACK_MEMORY_FAILED			ERR_CODE(GOODS_ACK_CODE_SEG,ERR_LEVEL_3,4)		//内存分配失败

******************************************************************************************************/

#ifndef __ERR_CODE_H
#define __ERR_CODE_H

#define OPERATE_SUCCESS 1
#define OPERATE_FAIL    0

#define ERR_LEVEL_0  0  //正常
#define ERR_LEVEL_1  100//致命故障
#define ERR_LEVEL_2  200//严重故障
#define ERR_LEVEL_3  300//一般故障
#define ERR_LEVEL_4  400//轻微故障

#define ERR_CODE(seg,level,num) (seg+level+num)

#define CARGO_MOTOR_CODE_SEG    (uint32_t)101000
#define CARGO_MOTOR_NORMAL      ERR_CODE(CARGO_MOTOR_CODE_SEG,0,0)          //(uint32_t)101000  //电机正常
#define CARGO_MOTOR_OUTIME      ERR_CODE(CARGO_MOTOR_CODE_SEG,ERR_LEVEL_3,1)//(uint32_t)101301  //电机超时出货
#define CARGO_MOTOR_BLOCK       ERR_CODE(CARGO_MOTOR_CODE_SEG,ERR_LEVEL_3,2)//(uint32_t)101302  //电机堵转
#define CARGO_MOTOR_LINKERR     ERR_CODE(CARGO_MOTOR_CODE_SEG,ERR_LEVEL_3,3)//(uint32_t)101303  //电机未连接
#define CARGO_CONTROL_LINKERR   ERR_CODE(CARGO_MOTOR_CODE_SEG,ERR_LEVEL_3,4)//(uint32_t)101204  //货道控制离线


#define GOODS_IR_CODE_SEG       (uint32_t)102000
#define GOODS_IR_NORMAL         ERR_CODE(GOODS_IR_CODE_SEG,0,0)  //红外正常
#define GOODS_IR_UNDETECT       ERR_CODE(GOODS_IR_CODE_SEG,ERR_LEVEL_4,1)  //红外未检测到商品
#define GOODS_IR_ERR            ERR_CODE(GOODS_IR_CODE_SEG,ERR_LEVEL_4,2)  //红外传感器故障
#define GOODS_IR_NOTPICK        ERR_CODE(GOODS_IR_CODE_SEG,ERR_LEVEL_4,3)  //检测到未取货

#define GOODS_INNERGATE_CODE_SEG           (uint32_t)108000
#define GOODS_INNERGATE_NORMAL             ERR_CODE(GOODS_INNERGATE_CODE_SEG,0,0)  //防盗门正常
#define GOODS_INNERGATE_UNFULLOPEN         ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,1)  //防盗门未完全打开
#define GOODS_INNERGATE_UNOPEN             ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,2)  //防盗门未打开
#define GOODS_INNERGATE_OFFLIN             ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,3)  //防盗门离线
#define GOODS_INNERGATE_UNFULLCLOSE        ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,4)  //防盗门未关闭
#define GOODS_INNERGATE_UNCLOSE            ERR_CODE(GOODS_INNERGATE_CODE_SEG,ERR_LEVEL_1,5)  //防盗门未关闭

#define GOODS_OUTERGATE_CODE_SEG     (uint32_t)109000
#define GOODS_OUTERGATE_NORMAL       ERR_CODE(GOODS_OUTERGATE_CODE_SEG,0,0)  //防盗门正常
#define GOODS_OUTERGATE_UNFULLOPEN   ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,1)  //防盗门未完全打开
#define GOODS_OUTERGATE_UNOPEN       ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,2)  //防盗门未打开
#define GOODS_OUTERGATE_OFFLIN       ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,3)  //防盗门离线
#define GOODS_OUTERGATE_UNFULLCLOSE  ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,4)  //防盗门未关闭
#define GOODS_OUTERGATE_UNCLOSE      ERR_CODE(GOODS_OUTERGATE_CODE_SEG,ERR_LEVEL_1,5)  //防盗门未关闭

#define GOODS_GATE_CODE_SEG     (uint32_t)110000
#define GOODS_GATE_NORMAL       ERR_CODE(GOODS_GATE_CODE_SEG,0,0)  //防盗门正常
#define GOODS_GATE_UNFULLOPEN   ERR_CODE(GOODS_GATE_CODE_SEG,ERR_LEVEL_1,1)  //防盗门未完全打开
#define GOODS_GATE_UNOPEN       ERR_CODE(GOODS_GATE_CODE_SEG,ERR_LEVEL_1,2)  //防盗门未打开
#define GOODS_GATE_OFFLIN       ERR_CODE(GOODS_GATE_CODE_SEG,ERR_LEVEL_1,3)  //防盗门离线
#define GOODS_GATE_UNFULLCLOSE  ERR_CODE(GOODS_GATE_CODE_SEG,ERR_LEVEL_1,4)  //防盗门未关闭
#define GOODS_GATE_UNCLOSE      ERR_CODE(GOODS_GATE_CODE_SEG,ERR_LEVEL_1,5)  //防盗门未关闭

#define LIFT_MOTOR_CODE_SEG      (uint32_t)111000
#define LIFT_MOTOR_NORMAL        ERR_CODE(LIFT_MOTOR_CODE_SEG,0,0)
#define LIFT_MOTOR_FAULT         ERR_CODE(LIFT_MOTOR_CODE_SEG,ERR_LEVEL_1,1)//升降电机故障
#define LIFT_MOTOR_OFFLINE       ERR_CODE(LIFT_MOTOR_CODE_SEG,ERR_LEVEL_1,2)//升降电机离线


#define TRANSPORT_MOTOR_CODE_SEG (uint32_t)112000
#define TRANSPORT_MOTOR_NORMAL    ERR_CODE(TRANSPORT_MOTOR_CODE_SEG,0,0)
#define TRANSPORT_MOTOR_FAULT     ERR_CODE(TRANSPORT_MOTOR_CODE_SEG,ERR_LEVEL_1,1)//升降电机故障
#define TRANSPORT_MOTOR_OFFLINE   ERR_CODE(TRANSPORT_MOTOR_CODE_SEG,ERR_LEVEL_1,2)//升降电机离线


#define OTA_ERR_CODE_SEG         (uint32_t)120000
#define OTA_NORMAL               ERR_CODE(OTA_ERR_CODE_SEG,0,0)
#define OTA_DOC_ILLEGAL          ERR_CODE(OTA_ERR_CODE_SEG,ERR_LEVEL_1,1)//文件非法
#define OTA_VER_IDENTIACAL       ERR_CODE(OTA_ERR_CODE_SEG,ERR_LEVEL_1,2)//固件版本相同
#define OTA_MEM_OVERFLOW         ERR_CODE(OTA_ERR_CODE_SEG,ERR_LEVEL_1,3)//内存空间不足
#define OTA_REQUEST_OUTTIME      ERR_CODE(OTA_ERR_CODE_SEG,ERR_LEVEL_1,4)//获取固件超时
#define OTA_SAVE_FAILURE         ERR_CODE(OTA_ERR_CODE_SEG,ERR_LEVEL_1,5)//数据保存失败
#define OTA_DATA_UNUSUAL         ERR_CODE(OTA_ERR_CODE_SEG,ERR_LEVEL_4,6)//数据异常
#define	OTA_MD5_FAILURE			 ERR_CODE(OTA_ERR_CODE_SEG,ERR_LEVEL_1,7)//MD5校验失败

//打饮类
#define MAKE_DRINK_CODE_SEG	    		(uint32_t)121000
#define	MAKE_DRINK_NORMAL				 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_0,0)		//121000	//打饮正常
#define	MAKE_DRINK_NO_LIQUOR		 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_3,1)		//121301	//未检测到酒
#define	MAKE_DRINK_NO_CUP				 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_3,2)		//121302	//未检测到杯
#define	MAKE_DRINK_REVISE				 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_3,3)		//121303	//打饮校正失败
#define	MAKE_DRINK_OUTIME				 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_3,4)		//121304	//打饮超时

#define	MAKE_DRINK_AIR_PRESSURE_ERR		 ERR_CODE(MAKE_DRINK_CODE_SEG,ERR_LEVEL_2,1)		//121205	//气压异常：可能是气泵不工作、管道破裂
//电控锁
#define	LOCK_CODE_SEG	           (uint32_t)122000
#define	LOCK_NORMAL		           ERR_CODE(LOCK_CODE_SEG,ERR_LEVEL_0,0)		//122000		//开锁正常		 	
#define	LOCK_BLOCK		           ERR_CODE(LOCK_CODE_SEG,ERR_LEVEL_3,1)		//122301		//开锁失败		
#define	LOCK_OUTIME		           ERR_CODE(LOCK_CODE_SEG,ERR_LEVEL_3,1)		//122202		//开锁超时	

//出货指令响应
#define	GOODS_ACK_CODE_SEG				(uint32_t)113000
#define	GOODS_ACK_NORMAL				ERR_CODE(GOODS_ACK_CODE_SEG,0,0)				//响应正常
#define	GOODS_ACK_MESSAGE_EXPIRATION	ERR_CODE(GOODS_ACK_CODE_SEG,ERR_LEVEL_3,1)  	//消息过期
#define	GOODS_ACK_TIME_NOT_SYNC			ERR_CODE(GOODS_ACK_CODE_SEG,ERR_LEVEL_3,2)		//时间未同步
#define	GOODS_ACK_SELL_BUSY				ERR_CODE(GOODS_ACK_CODE_SEG,ERR_LEVEL_3,3)		//出货忙
#define	GOODS_ACK_MEMORY_FAILED			ERR_CODE(GOODS_ACK_CODE_SEG,ERR_LEVEL_3,4)		//内存分配失败

#endif
