#ifndef __FUNCID_DEFINE_H
#define __FUNCID_DEFINE_H
typedef enum
{
	FUNCID_EXCEPTIONS=0x00,//异常响应
	FUNCID_HEART,          //心跳报文
	FUNCID_READPORT,       //读端口
	FUNCID_WRITEPORT,      //写端口
	FUNCID_CONNECT,        //建立连接
	FUNCID_REMOVECONNECT,  //删除连接
	FUNCID_RESET,          //复位设备
	FUNCID_IDCHECK,        //ID检测
  FUNCID_CYCLETRIGGER,
	FUNCID_STATETRIGGER,
	FUNCID_THRESTRIGGER,
	FUNCID_READINFO=0x0B,
	FUNCID_WAIT,
	FUNCID_RENEWTABLE,
	FUNCID_APPLYID,         //从机发起ID申请
	FUNCID_NONASK=0x0F,
}FuncIDEnumTypeDef;

typedef enum
{
 ERRID_UNDEFINEFUNCID=0x01,
 ERRID_NOTCONNECT,
 ERRID_CONNECT,
 ERRID_TRANSPORTERRO,
 ERRID_DATAUNMATE,
 ERRID_UNDEFINEDATA=0x06,
 ERRID_ASKOVERTIME
}ERRIDEnumTypeDef;



#endif
