#ifndef __MOTOR_GPIO_H
#define __MOTOR_GPIO_H

#include "sys.h"
#include "sensor.h"

//电机X轴控制引脚宏定义
#define MOTOR_CTL_X_A0_H 		PDout(3)=1
#define MOTOR_CTL_X_A1_H 		PDout(4)=1
#define MOTOR_CTL_X_A2_H 		PDout(5)=1
#define MOTOR_CTL_X_A0_L 		PDout(3)=0
#define MOTOR_CTL_X_A1_L 		PDout(4)=0
#define MOTOR_CTL_X_A2_L 		PDout(5)=0
#define MOTOR_CTL_X_EN_ENABLE	PDout(7)=1
#define MOTOR_CTL_X_EN_DISABLE	PDout(7)=0
#define MOTOR_CTL_X_LE_ENABLE	PDout(6)=1
#define	MOTOR_CTL_X_LE_DISABLE	PDout(6)=0
#define	MOTOR_CTL_X_E_SELECT_1	PBout(5)=0
#define	MOTOR_CTL_X_E_SELECT_2	PBout(5)=1

#define	MOTOR_X0_ENABLE			{MOTOR_CTL_X_A0_L;MOTOR_CTL_X_A1_L;MOTOR_CTL_X_A2_L;MOTOR_CTL_X_E_SELECT_1;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X1_ENABLE			{MOTOR_CTL_X_A0_H;MOTOR_CTL_X_A1_L;MOTOR_CTL_X_A2_L;MOTOR_CTL_X_E_SELECT_1;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X2_ENABLE			{MOTOR_CTL_X_A0_L;MOTOR_CTL_X_A1_H;MOTOR_CTL_X_A2_L;MOTOR_CTL_X_E_SELECT_1;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X3_ENABLE			{MOTOR_CTL_X_A0_H;MOTOR_CTL_X_A1_H;MOTOR_CTL_X_A2_L;MOTOR_CTL_X_E_SELECT_1;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X4_ENABLE			{MOTOR_CTL_X_A0_L;MOTOR_CTL_X_A1_L;MOTOR_CTL_X_A2_H;MOTOR_CTL_X_E_SELECT_1;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X5_ENABLE			{MOTOR_CTL_X_A0_H;MOTOR_CTL_X_A1_L;MOTOR_CTL_X_A2_H;MOTOR_CTL_X_E_SELECT_1;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X6_ENABLE			{MOTOR_CTL_X_A0_L;MOTOR_CTL_X_A1_H;MOTOR_CTL_X_A2_H;MOTOR_CTL_X_E_SELECT_1;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X7_ENABLE			{MOTOR_CTL_X_A0_H;MOTOR_CTL_X_A1_H;MOTOR_CTL_X_A2_H;MOTOR_CTL_X_E_SELECT_1;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X8_ENABLE			{MOTOR_CTL_X_A0_L;MOTOR_CTL_X_A1_L;MOTOR_CTL_X_A2_L;MOTOR_CTL_X_E_SELECT_2;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X9_ENABLE			{MOTOR_CTL_X_A0_H;MOTOR_CTL_X_A1_L;MOTOR_CTL_X_A2_L;MOTOR_CTL_X_E_SELECT_2;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X10_ENABLE		{MOTOR_CTL_X_A0_L;MOTOR_CTL_X_A1_H;MOTOR_CTL_X_A2_L;MOTOR_CTL_X_E_SELECT_2;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X11_ENABLE		{MOTOR_CTL_X_A0_H;MOTOR_CTL_X_A1_H;MOTOR_CTL_X_A2_L;MOTOR_CTL_X_E_SELECT_2;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X12_ENABLE		{MOTOR_CTL_X_A0_L;MOTOR_CTL_X_A1_L;MOTOR_CTL_X_A2_H;MOTOR_CTL_X_E_SELECT_2;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X13_ENABLE		{MOTOR_CTL_X_A0_H;MOTOR_CTL_X_A1_L;MOTOR_CTL_X_A2_H;MOTOR_CTL_X_E_SELECT_2;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X14_ENABLE		{MOTOR_CTL_X_A0_L;MOTOR_CTL_X_A1_H;MOTOR_CTL_X_A2_H;MOTOR_CTL_X_E_SELECT_2;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X15_ENABLE		{MOTOR_CTL_X_A0_H;MOTOR_CTL_X_A1_H;MOTOR_CTL_X_A2_H;MOTOR_CTL_X_E_SELECT_2;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_ENABLE;}
#define	MOTOR_X_ALL_DISABLE		{MOTOR_CTL_X_A0_L;MOTOR_CTL_X_A1_L;MOTOR_CTL_X_A2_L;MOTOR_CTL_X_E_SELECT_1;MOTOR_CTL_X_LE_DISABLE;MOTOR_CTL_X_EN_DISABLE;}

//电机Y轴控制引脚宏定义
#define MOTOR_CTL_Y_A0_H 		PGout(13)=1//PDout(2)=1
#define MOTOR_CTL_Y_A1_H		PGout(12)=1//PDout(1)=1
#define MOTOR_CTL_Y_A2_H		PGout(11)=1//PDout(0)=1
#define MOTOR_CTL_Y_A0_L 		PGout(13)=0//PDout(2)=0
#define MOTOR_CTL_Y_A1_L		PGout(12)=0//PDout(1)=0
#define MOTOR_CTL_Y_A2_L		PGout(11)//PDout(0)=0
#define MOTOR_CTL_Y_EN_ENABLE 	PGout(9)=1//PCout(11)=1
#define	MOTOR_CTL_Y_EN_DISABLE	PGout(9)=0//PCout(11)=0
#define MOTOR_CTL_Y_LE_ENABLE 	PGout(10)=1//PCout(12)=1
#define	MOTOR_CLT_Y_LE_DISABLE	PGout(10)=0//PCout(12)=0

#define	MOTOR_Y0_ENABLE			{MOTOR_CTL_Y_A0_L;MOTOR_CTL_Y_A1_L;MOTOR_CTL_Y_A2_L;MOTOR_CLT_Y_LE_DISABLE;MOTOR_CTL_Y_EN_ENABLE;}
#define	MOTOR_Y1_ENABLE			{MOTOR_CTL_Y_A0_H;MOTOR_CTL_Y_A1_L;MOTOR_CTL_Y_A2_L;MOTOR_CLT_Y_LE_DISABLE;MOTOR_CTL_Y_EN_ENABLE;}
#define	MOTOR_Y2_ENABLE			{MOTOR_CTL_Y_A0_L;MOTOR_CTL_Y_A1_H;MOTOR_CTL_Y_A2_L;MOTOR_CLT_Y_LE_DISABLE;MOTOR_CTL_Y_EN_ENABLE;}
#define	MOTOR_Y3_ENABLE			{MOTOR_CTL_Y_A0_H;MOTOR_CTL_Y_A1_H;MOTOR_CTL_Y_A2_L;MOTOR_CLT_Y_LE_DISABLE;MOTOR_CTL_Y_EN_ENABLE;}
#define	MOTOR_Y4_ENABLE			{MOTOR_CTL_Y_A0_L;MOTOR_CTL_Y_A1_L;MOTOR_CTL_Y_A2_H;MOTOR_CLT_Y_LE_DISABLE;MOTOR_CTL_Y_EN_ENABLE;}
#define	MOTOR_Y5_ENABLE			{MOTOR_CTL_Y_A0_H;MOTOR_CTL_Y_A1_L;MOTOR_CTL_Y_A2_H;MOTOR_CLT_Y_LE_DISABLE;MOTOR_CTL_Y_EN_ENABLE;}
#define	MOTOR_Y6_ENABLE			{MOTOR_CTL_Y_A0_L;MOTOR_CTL_Y_A1_H;MOTOR_CTL_Y_A2_H;MOTOR_CLT_Y_LE_DISABLE;MOTOR_CTL_Y_EN_ENABLE;}
#define	MOTOR_Y7_ENABLE			{MOTOR_CTL_Y_A0_H;MOTOR_CTL_Y_A1_H;MOTOR_CTL_Y_A2_H;MOTOR_CLT_Y_LE_DISABLE;MOTOR_CTL_Y_EN_ENABLE;}
#define	MOTOR_Y_ALL_DISABLE		{MOTOR_CTL_Y_A0_L;MOTOR_CTL_Y_A1_L;MOTOR_CTL_Y_A2_L;MOTOR_CLT_Y_LE_DISABLE;MOTOR_CTL_Y_EN_DISABLE;}



void MotorGpio_GpioInit(void);
void MotorGpio_RestAll_Y(void);
void MotorGpio_RestAll_X(void);
void MotorGpio_Set_X(uint8_t ch);
void MotorGpio_Set_Y(uint8_t ch);
float MotorGpio_GetMotorCurrent(void);




#endif
