#ifndef __SYSTEM_H
#define __SYSTEM_H
#include "task_manage.h"

#include "step_motor.h"
#include "signal_scan.h"
#include "motor_drive.h"
#include "can_app.h"
//#include "lift_motor.h"
//#include "lift_control.h"
#include "cryogen_drive.h"
#include "protocol_app.h"
#include "cloud_protocol.h"
#include "sell_app.h"
#include "led.h"
#include "iap.h"
//#include "speed_motor.h"
//#include "gate_control.h"
#include "tempcontrol.h"
#include "sys_config.h"
#include "cargo_motor_test.h"
#include "at_7s4.h"
//#include "mqtt_manage.h"
#include "ota.h"
#include "time_stamp.h"
#include "rtc.h"
#include "watchdog.h"
#include "wireless_module_init.h"
#include "NetworkModule.h"
#include "lock_app.h"
#include "basic_gate_motor.h"
#include "dgus_recive.h"
#include "dgus_app.h"
#include "rtc.h"
#include "wireless_module_init.h"
#include "NetworkModule.h"
#include "mqtt_config.h"
#include "mqtt_qos1.h"
#include "mqtt_connect.h"
#include "motor_test.h"

void System_Init(void);
void System_TaskRun(void);

#endif
